### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by gaokevin1**
Create a profile README.

## Related Issues

Fixes https://github.com/descope/etc/issues/3167

## Related PRs

| branch       | PR         |
| ------------ | ---------- |
| service a PR | Link to PR |
| service b PR | Link to PR |

## Description

A few sentences describing the overall goals of the pull request's commits.

## Must

- [ ] Tests
- [ ] Documentation (if applicable)

### CODE REVIEW

**Review by dorsha — COMMENTED** [review]
Is this just a template right?

**Comment by gaokevin1** [comment]
Yes it's not ready for review yet @dorsha I will request a review once it's complete.

**Comment by dorsha** [comment]
Cool

**Comment by dorsha** [comment]
@gaokevin1 any update?

**Comment by gaokevin1** [comment]
Was working on a Webflow Template yesterday will complete this after I'm done with that @dorsha

**Review by chris4490 — APPROVED** [review]

**Pull request merged**
